In [76]:
# Dependencies
import pandas as pd
from pathlib import Path

In [77]:
# Create a reference the CSV file desired
csv_path = Path("Resources/JC-202305-citibike-tripdata.csv")

# Read the CSV into a Pandas DataFrame
May2023_df = pd.read_csv(csv_path, low_memory=False)

# Print data to the screen
May2023_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,BC145343639B5E5B,classic_bike,2023-05-31 12:27:28,2023-05-31 12:38:36,Pershing Field,JC024,Newport PATH,JC066,40.742675,-74.051806,40.727224,-74.033759,member
1,A0CE41F47514FF5C,classic_bike,2023-05-01 18:12:37,2023-05-01 18:29:03,Pershing Field,JC024,Baldwin at Montgomery,JC020,40.742638,-74.051815,40.723659,-74.064194,casual
2,D588077E3D7E2AFD,electric_bike,2023-05-28 17:37:58,2023-05-28 18:39:39,Pershing Field,JC024,Pershing Field,JC024,40.742677,-74.051789,40.742677,-74.051789,casual
3,89AC48A5584B2DB4,classic_bike,2023-05-27 21:01:37,2023-05-27 21:13:16,Pershing Field,JC024,Manila & 1st,JC082,40.742677,-74.051789,40.721651,-74.042884,member
4,709E0B11AB4A0E6C,classic_bike,2023-05-22 12:38:54,2023-05-22 13:02:13,Pershing Field,JC024,Jersey & 3rd,JC074,40.742677,-74.051789,40.723332,-74.045953,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95997,9549398286BB59B5,docked_bike,2023-05-27 13:24:51,2023-05-27 13:51:18,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,Newport Pkwy,JC008,40.736982,-74.027781,40.728745,-74.032108,casual
95998,AB0790683044D89E,classic_bike,2023-05-18 17:12:07,2023-05-18 17:25:02,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,Warren St,JC006,40.736982,-74.027781,40.721124,-74.038051,member
95999,68226FA538A405CA,classic_bike,2023-05-05 18:44:57,2023-05-05 18:56:15,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,Warren St,JC006,40.736982,-74.027781,40.721124,-74.038051,member
96000,CABAC21C0F0140A5,classic_bike,2023-05-16 11:56:11,2023-05-16 12:04:04,Columbus Drive,JC014,Newport Pkwy,JC008,40.718355,-74.038914,40.728745,-74.032108,member
96001,4AABD797EF6F7BB2,classic_bike,2023-05-30 11:04:46,2023-05-30 11:13:54,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,Warren St,JC006,40.736982,-74.027781,40.721124,-74.038051,member

In [78]:
# Check Count

May2023_df.count()

ride_id               96002
rideable_type         96002
started_at            96002
ended_at              96002
start_station_name    96002
start_station_id      96002
end_station_name      95736
end_station_id        95736
start_lat             96002
start_lng             96002
end_lat               95865
end_lng               95865
member_casual         96002
dtype: int64

In [79]:
# clean May2023_df & Check Count

May2023_cleaned_df = May2023_df.dropna(how="any")
May2023_cleaned_df.count()

ride_id               95736
rideable_type         95736
started_at            95736
ended_at              95736
start_station_name    95736
start_station_id      95736
end_station_name      95736
end_station_id        95736
start_lat             95736
start_lng             95736
end_lat               95736
end_lng               95736
member_casual         95736
dtype: int64

In [80]:
# Export file as .csv

May2023_cleaned_df.to_csv("Resources/May2023_citibike_cleaned.csv", index=False, header=True)

In [81]:
# Create a reference the CSV file desired
csv_path = Path("Resources/JC-202306-citibike-tripdata.csv")

# Read the CSV into a Pandas DataFrame
June2023_df = pd.read_csv(csv_path, low_memory=False)

# Print the first five rows of data to the screen
June2023_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,37BE5FCB1A385CDA,classic_bike,2023-06-27 16:06:27,2023-06-27 16:10:27,Hilltop,JC019,Christ Hospital,JC034,40.731115,-74.057468,40.734786,-74.050444,casual
1,9C96B4C6CBBB31AD,classic_bike,2023-06-24 10:46:58,2023-06-24 10:55:27,Baldwin at Montgomery,JC020,Hamilton Park,JC009,40.723473,-74.064338,40.727596,-74.044247,member
2,C91293605D4BEC07,electric_bike,2023-06-04 20:30:13,2023-06-04 20:34:31,Hilltop,JC019,Brunswick St,JC023,40.731169,-74.057574,40.724176,-74.050656,member
3,2920063442116A46,classic_bike,2023-06-08 19:10:06,2023-06-08 19:13:05,Baldwin at Montgomery,JC020,Astor Place,JC077,40.723499,-74.064335,40.719282,-74.071262,member
4,E205FD8C18BA263A,classic_bike,2023-06-23 18:53:51,2023-06-23 19:17:50,Baldwin at Montgomery,JC020,Adams St & 11 St,HB507,40.723511,-74.064277,40.750916,-74.033541,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
97018,2C69F8EF2A1BDD90,classic_bike,2023-06-30 19:41:00,2023-06-30 23:07:31,Washington St,JC098,Newport Pkwy,JC008,40.724294,-74.035483,40.728745,-74.032108,casual
97019,43E592256BC287BB,classic_bike,2023-06-20 18:55:02,2023-06-20 19:01:47,Washington St,JC098,Southwest Park - Jackson St & Observer Hwy,HB401,40.724273,-74.035498,40.737551,-74.041664,member
97020,4C3A7521689C560C,electric_bike,2023-06-22 19:24:22,2023-06-22 19:30:03,9 St HBLR - Jackson St & 8 St,HB305,Willow Ave & 12 St,HB505,40.747907,-74.038412,40.751867,-74.030377,casual
97021,9AAA8F2E630456E7,classic_bike,2023-06-30 13:34:09,2023-06-30 13:38:34,9 St HBLR - Jackson St & 8 St,HB305,Willow Ave & 12 St,HB505,40.747971,-74.038413,40.751867,-74.030377,casual
97022,064CE90800E9C21F,classic_bike,2023-06-13 17:23:31,2023-06-13 17:28:01,9 St HBLR - Jackson St & 8 St,HB305,Willow Ave & 12 St,HB505,40.748000,-74.038375,40.751867,-74.030377,casual

In [82]:
# Check Count

June2023_df.count()

ride_id               97023
rideable_type         97023
started_at            97023
ended_at              97023
start_station_name    96968
start_station_id      96968
end_station_name      96662
end_station_id        96662
start_lat             97023
start_lng             97023
end_lat               96935
end_lng               96935
member_casual         97023
dtype: int64

In [83]:
# clean June2023_df & Check Count

June2023_cleaned_df = June2023_df.dropna(how="any")
June2023_cleaned_df.count()

ride_id               96662
rideable_type         96662
started_at            96662
ended_at              96662
start_station_name    96662
start_station_id      96662
end_station_name      96662
end_station_id        96662
start_lat             96662
start_lng             96662
end_lat               96662
end_lng               96662
member_casual         96662
dtype: int64

In [84]:
# Export file as .csv

June2023_cleaned_df.to_csv("Resources/June2023_citibike_cleaned.csv.", index=False, header=True)

In [85]:
# Create a reference the CSV file desired
csv_path = Path("Resources/JC-202307-citibike-tripdata.csv")

# Read the CSV into a Pandas DataFrame
July2023_df = pd.read_csv(csv_path, low_memory=False)

# Print the first five rows of data to the screen
July2023_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,7A68381621C25F78,classic_bike,2023-07-17 17:16:34,2023-07-17 17:20:52,Astor Place,JC077,Communipaw & Berry Lane,JC084,40.719225,-74.071281,40.714358,-74.066611,member
1,0F814CA67B2FA120,classic_bike,2023-07-26 19:40:15,2023-07-26 19:44:37,Adams St & 2 St,HB407,9 St HBLR - Jackson St & 8 St,HB305,40.739727,-74.036866,40.747907,-74.038412,member
2,775A38967EBF5FB4,electric_bike,2023-07-01 12:12:22,2023-07-01 12:27:45,McGinley Square,JC055,Riverview Park,JC057,40.725340,-74.067622,40.744319,-74.043991,member
3,D93B742DCE1C1447,classic_bike,2023-07-20 19:10:18,2023-07-20 19:17:22,Baldwin at Montgomery,JC020,Brunswick St,JC023,40.723455,-74.064359,40.724176,-74.050656,member
4,AA7A6863B4B92169,electric_bike,2023-07-07 19:33:59,2023-07-07 19:58:17,Baldwin at Montgomery,JC020,Mama Johnson Field - 4 St & Jackson St,HB404,40.723659,-74.064194,40.743140,-74.040041,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...
106603,944F5CD711E7688E,classic_bike,2023-07-25 18:21:52,2023-07-25 18:34:38,Van Vorst Park,JC035,Newport Pkwy,JC008,40.718489,-74.047727,40.728745,-74.032108,member
106604,4665B542F79F8C43,electric_bike,2023-07-26 22:22:20,2023-07-26 22:26:20,Van Vorst Park,JC035,Warren St,JC006,40.718489,-74.047727,40.721124,-74.038051,member
106605,789D45FDEBC19E83,classic_bike,2023-07-31 07:57:29,2023-07-31 08:03:58,Van Vorst Park,JC035,Newport Pkwy,JC008,40.718422,-74.047691,40.728745,-74.032108,member
106606,FFBE463288D36C2A,classic_bike,2023-07-07 17:52:09,2023-07-07 18:00:14,Van Vorst Park,JC035,Warren St,JC006,40.718489,-74.047727,40.721124,-74.038051,member
106607,4DACECF4EBBEB60C,classic_bike,2023-07-26 20:54:16,2023-07-26 21:05:33,Van Vorst Park,JC035,Newport Pkwy,JC008,40.718489,-74.047727,40.728745,-74.032108,member

In [86]:
# Check Count

July2023_df.count()

ride_id               106608
rideable_type         106608
started_at            106608
ended_at              106608
start_station_name    106601
start_station_id      106601
end_station_name      106216
end_station_id        106216
start_lat             106608
start_lng             106608
end_lat               106486
end_lng               106486
member_casual         106608
dtype: int64

In [87]:
# clean July2023_df & Check Count

July2023_cleaned_df = July2023_df.dropna(how="any")
July2023_cleaned_df.count()

ride_id               106216
rideable_type         106216
started_at            106216
ended_at              106216
start_station_name    106216
start_station_id      106216
end_station_name      106216
end_station_id        106216
start_lat             106216
start_lng             106216
end_lat               106216
end_lng               106216
member_casual         106216
dtype: int64

In [88]:
# Export file as .csv

July2023_cleaned_df.to_csv("Resources/July2023_citibike_cleaned.csv", index=False, header=True)

In [89]:
frames  = [May2023_cleaned_df, June2023_cleaned_df, July2023_cleaned_df]
May_June_July_cleaned_combined_df =  pd.concat(frames)
May_June_July_cleaned_combined_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,BC145343639B5E5B,classic_bike,2023-05-31 12:27:28,2023-05-31 12:38:36,Pershing Field,JC024,Newport PATH,JC066,40.742675,-74.051806,40.727224,-74.033759,member
1,A0CE41F47514FF5C,classic_bike,2023-05-01 18:12:37,2023-05-01 18:29:03,Pershing Field,JC024,Baldwin at Montgomery,JC020,40.742638,-74.051815,40.723659,-74.064194,casual
2,D588077E3D7E2AFD,electric_bike,2023-05-28 17:37:58,2023-05-28 18:39:39,Pershing Field,JC024,Pershing Field,JC024,40.742677,-74.051789,40.742677,-74.051789,casual
3,89AC48A5584B2DB4,classic_bike,2023-05-27 21:01:37,2023-05-27 21:13:16,Pershing Field,JC024,Manila & 1st,JC082,40.742677,-74.051789,40.721651,-74.042884,member
4,709E0B11AB4A0E6C,classic_bike,2023-05-22 12:38:54,2023-05-22 13:02:13,Pershing Field,JC024,Jersey & 3rd,JC074,40.742677,-74.051789,40.723332,-74.045953,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
106603,944F5CD711E7688E,classic_bike,2023-07-25 18:21:52,2023-07-25 18:34:38,Van Vorst Park,JC035,Newport Pkwy,JC008,40.718489,-74.047727,40.728745,-74.032108,member
106604,4665B542F79F8C43,electric_bike,2023-07-26 22:22:20,2023-07-26 22:26:20,Van Vorst Park,JC035,Warren St,JC006,40.718489,-74.047727,40.721124,-74.038051,member
106605,789D45FDEBC19E83,classic_bike,2023-07-31 07:57:29,2023-07-31 08:03:58,Van Vorst Park,JC035,Newport Pkwy,JC008,40.718422,-74.047691,40.728745,-74.032108,member
106606,FFBE463288D36C2A,classic_bike,2023-07-07 17:52:09,2023-07-07 18:00:14,Van Vorst Park,JC035,Warren St,JC006,40.718489,-74.047727,40.721124,-74.038051,member
106607,4DACECF4EBBEB60C,classic_bike,2023-07-26 20:54:16,2023-07-26 21:05:33,Van Vorst Park,JC035,Newport Pkwy,JC008,40.718489,-74.047727,40.728745,-74.032108,member

In [90]:
May_June_July_cleaned_combined_df.count()

ride_id               298614
rideable_type         298614
started_at            298614
ended_at              298614
start_station_name    298614
start_station_id      298614
end_station_name      298614
end_station_id        298614
start_lat             298614
start_lng             298614
end_lat               298614
end_lng               298614
member_casual         298614
dtype: int64

In [91]:
# Export file as .csv

May_June_July_cleaned_combined_df.to_csv("Resources/May_June_July_cleaned_combined_df.csv", index=False, header=True)

In [92]:
May_June_July_cleaned_combined_df['start_station_id'].value_counts().head(10)

start_station_id
JC115    14705
HB102    12383
HB103    10823
HB101     7904
JC066     7615
HB201     7361
HB105     7313
JC009     6685
JC008     6626
HB502     5779
Name: count, dtype: int64

In [93]:
combined_top_ten_starting_df = May_June_July_cleaned_combined_df.loc[May_June_July_cleaned_combined_df['start_station_id'].isin(['JC115', 'HB102', 'HB103', 'HB101', 'JC066', 'HB201', 'HB105', 'JC009', 'JC008', 'HB502'])]
combined_top_ten_starting_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
25,31AE38E870A8C49F,classic_bike,2023-05-02 18:08:04,2023-05-02 18:13:47,Hoboken Terminal - River St & Hudson Pl,HB102,6 St & Grand St,HB302,40.736365,-74.028986,40.744398,-74.034501,member
35,1659DA6BB6C03BA1,classic_bike,2023-05-15 16:23:41,2023-05-15 16:26:33,Hoboken Terminal - River St & Hudson Pl,HB102,Hudson St & 4 St,HB607,40.736068,-74.029127,40.740973,-74.028603,member
37,B38FEDF86081BB09,electric_bike,2023-05-27 15:25:42,2023-05-27 15:28:07,Hoboken Terminal - River St & Hudson Pl,HB102,Hudson St & 4 St,HB607,40.736068,-74.029127,40.740973,-74.028603,member
38,4FC3A1F7224963AD,electric_bike,2023-05-10 17:41:45,2023-05-10 17:44:16,Hoboken Terminal - River St & Hudson Pl,HB102,Hudson St & 4 St,HB607,40.736068,-74.029127,40.740973,-74.028603,member
50,D39363573C3B9029,classic_bike,2023-05-26 16:42:38,2023-05-26 16:44:56,City Hall - Washington St & 1 St,HB105,Clinton St & Newark St,HB409,40.737360,-74.030970,40.737430,-74.035710,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
106513,E8D2F796B85EF5DE,classic_bike,2023-07-05 00:45:02,2023-07-05 00:59:11,Hamilton Park,JC009,Heights Elevator,JC059,40.727593,-74.044358,40.748716,-74.040443,casual
106514,5EA084016787E93E,classic_bike,2023-07-17 14:04:34,2023-07-17 14:19:40,Hamilton Park,JC009,Heights Elevator,JC059,40.727437,-74.044244,40.748716,-74.040443,casual
106515,E7D33ABDA59C72E7,electric_bike,2023-07-07 02:28:37,2023-07-07 02:51:03,Hamilton Park,JC009,Heights Elevator,JC059,40.727596,-74.044247,40.748716,-74.040443,casual
106516,0DD0F2681C4BC9A0,classic_bike,2023-07-08 22:48:42,2023-07-08 23:58:22,Hamilton Park,JC009,Heights Elevator,JC059,40.727537,-74.044162,40.748716,-74.040443,casual
106517,04141AD68D0F481D,classic_bike,2023-07-26 15:22:55,2023-07-26 15:30:33,Hamilton Park,JC009,6 St & Grand St,HB302,40.727589,-74.044237,40.744398,-74.034501,member

In [94]:
combined_top_ten_starting_df.count()

ride_id               87194
rideable_type         87194
started_at            87194
ended_at              87194
start_station_name    87194
start_station_id      87194
end_station_name      87194
end_station_id        87194
start_lat             87194
start_lng             87194
end_lat               87194
end_lng               87194
member_casual         87194
dtype: int64

In [95]:
# Export file as .csv

combined_top_ten_starting_df.to_csv("Resources/combined_top_ten_starting_df.csv", index=False, header=True)

In [96]:
May_June_July_cleaned_combined_df['start_station_id'].value_counts().tail(10)

start_station_id
5989.02    1
6072.06    1
6644.08    1
6717.06    1
5712.03    1
5746.14    1
5593.02    1
5411.08    1
6535.04    1
5351.07    1
Name: count, dtype: int64

In [97]:
bottom_ten_stations = {
    'start_station_id': ['JC115', 'HB102', 'HB103', 'HB101', 'JC066', 'HB201', 'HB105', 'JC009', 'JC008', 'HB502']
} 

combined_bottom_ten_starting_df = May_June_July_cleaned_combined_df.loc[May_June_July_cleaned_combined_df['start_station_id'].isin(['J5989.02', '6072.06', '6644.08', '6717.06', '5712.03', '5746.14', '5593.02', '5411.08', '6535.04', '5351.07'])]
combined_bottom_ten_starting_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
33010,8743BE53DDD915D1,classic_bike,2023-05-26 11:58:17,2023-05-26 12:14:34,W 34 St & Hudson Blvd E,6535.04,Cleveland Pl & Spring St,5492.05,40.735354,-74.046973,40.722104,-73.997249,member
33096,16A08B322E1BF0F7,classic_bike,2023-05-26 10:14:38,2023-05-26 10:26:12,Driggs Ave & N 9 St,5411.08,Cleveland Pl & Spring St,5492.05,40.735354,-74.046973,40.722104,-73.997249,member
33336,0432950E336838D2,classic_bike,2023-05-23 20:15:52,2023-05-23 20:47:02,E 2 St & 2 Ave,5593.02,George St & Wilson Ave,4906.07,40.735354,-74.046973,40.702997,-73.929970,member
33902,828A3908A4A3D3CB,classic_bike,2023-05-23 12:41:55,2023-05-23 12:48:40,E 11 St & 1 Ave,5746.14,Greenwich Ave & 8 Ave,6072.06,40.735354,-74.046973,40.739017,-74.002638,member
33944,256851F4DE1FC002,classic_bike,2023-05-23 13:50:24,2023-05-23 14:07:18,Cooper Square & Astor Pl,5712.03,7 Ave & Central Park South,6912.01,40.735354,-74.046973,40.766741,-73.979069,member
35025,490234F8EC50FE02,classic_bike,2023-05-25 19:17:50,2023-05-25 19:37:16,9 Ave & W 45 St,6717.06,W 51 St & 6 Ave,6740.10,40.735354,-74.046973,40.760660,-73.980420,casual
35580,AFF80E596BEC7138,classic_bike,2023-05-25 19:55:23,2023-05-25 20:03:54,9 Ave & W 39 St,6644.08,W 45 St & 8 Ave,6676.02,40.735354,-74.046973,40.759291,-73.988597,casual
37515,A838ED866ED431FD,classic_bike,2023-05-23 13:40:56,2023-05-23 13:46:44,Greenwich Ave & 8 Ave,6072.06,Cooper Square & Astor Pl,5712.03,40.735354,-74.046973,40.729515,-73.990753,member
101490,667518E9B3709E09,classic_bike,2023-07-19 12:13:17,2023-07-19 12:16:50,Walker St & Baxter St,5351.07,Catherine St & Monroe St,5128.04,40.731071,-74.064446,40.711174,-73.996826,member

In [98]:
# Export file as .csv

combined_bottom_ten_starting_df.to_csv("Resources/combined_bottom_ten_starting_df.csv", index=False, header=True)